FIX: Add --upgrade-to-write-transaction to error message, too

diff --git a/bin/miniDB b/bin/miniDB
--- a/bin/miniDB
+++ b/bin/miniDB
@@ -199,7 +199,7 @@ multipleActionsError()
 }
 multipleTransactionsError()
 {
-    echo >&2 "ERROR: --transactional cannot be combined with the --start-read-transaction|--start-write-transaction|--within-transaction|--end-transaction|--abort-write-transaction set."
+    echo >&2 "ERROR: --transactional cannot be combined with the --start-read-transaction|--start-write-transaction|--upgrade-to-write-transaction|--within-transaction|--end-transaction|--abort-write-transaction set."
     echo >&2
     printShortUsage "$1" >&2
     exit 2
