Tests: Add test for querying with empty key

diff --git a/bin/miniDB b/bin/miniDB
--- a/bin/miniDB
+++ b/bin/miniDB
@@ -153,6 +153,9 @@ do
 			    echo >&2
 			    printShortUsage "$0" >&2
 			    exit 2
+			elif [ ! "$key" ]; then
+			    echo >&2 'ERROR: Key must not be empty.'
+			    exit 2
 			fi
 			;;
 	--columns|-c)	shift
