Refactoring: Extract ACTIONS constant (in script and tests)

diff --git a/bin/miniDB b/bin/miniDB
--- a/bin/miniDB
+++ b/bin/miniDB
@@ -222,9 +222,10 @@ containsTab()
 {
     [[ "${1?}" =~ $'\t' ]]
 }
+readonly ACTIONS='--update, --delete, --truncate, --drop, --[read-]command, --each, --query[-keys], --unescape, --start-read-transaction, --start-write-transaction, --upgrade-to-write-transaction, --within-transaction, --end-transaction, --abort-write-transaction'
 multipleActionsError()
 {
-    echo >&2 "ERROR: Only one of --update, --delete, --truncate, --drop, --[read-]command, --each, --query[-keys], --unescape, --start-read-transaction, --start-write-transaction, --upgrade-to-write-transaction, --within-transaction, --end-transaction, --abort-write-transaction allowed."
+    echo >&2 "ERROR: Only one of $ACTIONS allowed."
     echo >&2
     printShortUsage "$1" >&2
     exit 2
