FIX: Update multipleActionsError() with transactional actions, add test
Also, the other previously added actions (query-key, each, unescape) were forgotten there as well.

diff --git a/bin/miniDB b/bin/miniDB
--- a/bin/miniDB
+++ b/bin/miniDB
@@ -192,7 +192,7 @@ containsTab()
 }
 multipleActionsError()
 {
-    echo >&2 "ERROR: Only one of --update, --query allowed."
+    echo >&2 "ERROR: Only one of --update, --delete, --drop, --each, --query[-keys], --unescape, --start-read-transaction, --start-write-transaction, --upgrade-to-write-transaction, --within-transaction, --end-transaction, --abort-write-transaction allowed."
     echo >&2
     printShortUsage "$1" >&2
     exit 2
