WIP: Add COL1++|N++ parsing and non-overflowing increment update

diff --git a/bin/miniDB b/bin/miniDB
--- a/bin/miniDB
+++ b/bin/miniDB
@@ -30,7 +30,7 @@ printShortUsage()
     printf 'Usage: %q %s\n' "$(basename "$1")" '... (--start-read-transaction OWNER-ID [--transaction-timeout TX-TIMEOUT]|--start-write-transaction OWNER-ID [--transaction-timeout TX-TIMEOUT]|--upgrade-to-write-transaction OWNER-ID [--transaction-timeout TX-TIMEOUT]|--end-transaction OWNER-ID|--abort-write-transaction OWNER-ID) [--timeout SECONDS] [--silence-transaction-errors]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... [(-t|--transactional [--transaction-timeout TX-TIMEOUT]|--within-transaction|-T|--no-transaction) [--timeout SECONDS] [--silence-transaction-errors]] ...'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -u|--update RECORD'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -u|--update KEY -v|--column COL1=VALUE1|N=VALUE-N [...]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -u|--update KEY -v|--column COL1=VALUE1|N=VALUE-N|COL1++|N++ [...]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -d|--delete KEY'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -C|--truncate'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -D|--drop'
@@ -83,6 +83,14 @@ HELPDESCRIPTION
 				COL1=VALUE1 columns that match the passed schema
 				N=VALUE-N   columns with the passed indices,
 				starting with 0 for KEY, 1 for COL1
+    --column|-v COL1++|N++
+				Instead of updating the entire record, just
+				atomically increment specific columns:
+				COL1++ columns that match the passed schema
+				N++    columns with the passed indices,
+				starting with 0 for KEY, 1 for COL1
+				An empty / non-existing column will be treated
+				like 0 and incremented to 1.
     --delete|-d KEY		Delete any existing record for KEY.
     --truncate|-C		Delete all existing records; just keep the
 				schema. Creates the table if it doesn't exist
@@ -299,6 +307,7 @@ typeset -a lockControllerArgs=()
 isSilenceTransactionErrors=
 isNeedEval=
 typeset -a commands=()
+readonly INCREMENT_VALUE=$'\t'	# Use the forbidden tab character as an indicator that the column should be incremented.
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -352,21 +361,26 @@ do
 			containsTab "$line" || line="${line}"$'\t'   # Need at least one tab separator.
 			;;
 	--column|-v)	shift
-			column="${1%%=*}"
-			value="${1#*=}"
-			if [[ ! "$1" =~ = ]] || [ -z "$column" ]; then
-			    echo 'ERROR: Column values must be specified as COL1=VALUE1 or N=VALUE-N.'
-			    echo
-			    printUsage "$0"
-			    exit 2
-			elif containsTab "$value"; then
-			    echo 'ERROR: VALUE cannot contain tab characters.'
-			    echo
-			    printUsage "$0"
-			    exit 2
-			fi >&2
+			if [[ "$1" =~ \+\+$ ]]; then
+			    column="${1%++}"
+			    updatedColumnValues["$column"]="$INCREMENT_VALUE"
+			else
+			    column="${1%%=*}"
+			    value="${1#*=}"
+			    if [[ ! "$1" =~ = ]] || [ -z "$column" ]; then
+				echo 'ERROR: Column values must be specified as COL1=VALUE1 or N=VALUE-N (or increment via COL1++ / N++).'
+				echo
+				printUsage "$0"
+				exit 2
+			    elif containsTab "$value"; then
+				echo 'ERROR: VALUE cannot contain tab characters.'
+				echo
+				printUsage "$0"
+				exit 2
+			    fi >&2
+			    updatedColumnValues["$column"]="$(escapeNewline "$value")"
+			fi
 			queriedColumns+=("$column")
-			updatedColumnValues["$column"]="$(escapeNewline "$value")"
 			shift
 			;;
 	--delete|-d)	shift; [ "$action" ] && multipleActionsError "$0"; action='delete'; key="$1"; shift
@@ -668,12 +682,25 @@ updateSpecifiedColumns()
 	    exit 2
 	fi
 	local sedUpdatePattern=
-	local literalValue="${updatedColumnValues[$c]}"
-	literalValue="${literalValue//\\/\\\\}"
-	literalValue="${literalValue//&/\\&}"
 	[ $c -ge 1 ] && sedUpdatePattern="${SED_PRECEDING_COLUMN_PATTERN}\\{${c}\\}"
-	sedUpdateColumnsArguments+=(-e "s#^\\(${sedUpdatePattern}\\)${SED_ONE_COLUMN_PATTERN}#\\1${literalValue//#/\\#}#")
-
+	if [ "${updatedColumnValues[$c]}" = "$INCREMENT_VALUE" ]; then
+	    sedUpdateColumnsArguments+=(
+		-e "s#^\\(${sedUpdatePattern}\\)"'\([0-9]*\)8\($\|\t\)#\1\39\4#'
+		-e "s#^\\(${sedUpdatePattern}\\)"'\([0-9]*\)7\($\|\t\)#\1\38\4#'
+		-e "s#^\\(${sedUpdatePattern}\\)"'\([0-9]*\)6\($\|\t\)#\1\37\4#'
+		-e "s#^\\(${sedUpdatePattern}\\)"'\([0-9]*\)5\($\|\t\)#\1\36\4#'
+		-e "s#^\\(${sedUpdatePattern}\\)"'\([0-9]*\)4\($\|\t\)#\1\35\4#'
+		-e "s#^\\(${sedUpdatePattern}\\)"'\([0-9]*\)3\($\|\t\)#\1\34\4#'
+		-e "s#^\\(${sedUpdatePattern}\\)"'\([0-9]*\)2\($\|\t\)#\1\33\4#'
+		-e "s#^\\(${sedUpdatePattern}\\)"'\([0-9]*\)1\($\|\t\)#\1\32\4#'
+		-e "s#^\\(${sedUpdatePattern}\\)"'\([0-9]*\)0\($\|\t\)#\1\31\4#'
+	    )
+	else
+	    local literalValue="${updatedColumnValues[$c]}"
+	    literalValue="${literalValue//\\/\\\\}"
+	    literalValue="${literalValue//&/\\&}"
+	    sedUpdateColumnsArguments+=(-e "s#^\\(${sedUpdatePattern}\\)${SED_ONE_COLUMN_PATTERN}#\\1${literalValue//#/\\#}#")
+	fi
 	[ $c -gt $highestIndex ] && highestIndex=$c
     done
     typeset -a sedEnsureColumnsArguments=()
