Add --upgrade-to-write-transaction

diff --git a/lib/miniTX b/lib/miniTX
--- a/lib/miniTX
+++ b/lib/miniTX
@@ -101,6 +101,28 @@ case "$method" in
 	fi
 	createLock
 	;;
+    TX-UPGRADE)
+	if existsLock; then
+	    if [ "$lockOwner" = "$thisTransactionOwner" ]; then
+		if isLockExpired; then
+		    printf >&2 'Warning: Current transaction timed out %d second%s ago.\n' "$diff" "$diffPlural"
+		elif [ "$lockMode" = 'write' ]; then
+		    echo >&2 'Note: Current transaction already is a write transaction, no need to upgrade.'
+		fi
+		thisTransactionExpiry=$((NOW + thisTransactionTimeout))
+		createLock
+	    elif isLockExpired; then
+		printf >&2 'ERROR: Another %s has started already (and timed out %d second%s ago).\n' "$(getTransactionDescription)" "$diff" "$diffPlural"
+		exit 6
+	    else
+		printf >&2 'ERROR: Another %s is already in progress.\n' "$(getTransactionDescription)"
+		exit 6
+	    fi
+	else
+	    echo >&2 'ERROR: Not inside a transaction, or the transaction has timed out and another transaction was completed.'
+	    exit 6
+	fi
+	;;
     TX-END)
 	if existsLock; then
 	    if [ "$lockOwner" = "$thisTransactionOwner" -o "$lockOwner" = '*' ]; then
